export const statusMeta: Record<
  string,
  { label: string; type: 'primary' | 'success' | 'info' | 'warning' | 'danger' }
> = {
  ACTIVE: { label: '在读', type: 'success' },
  LEAVE: { label: '请假中', type: 'warning' },
  SUSPENDED: { label: '休学', type: 'danger' },
  APPROVING: { label: '审批中', type: 'warning' },
  APPROVED: { label: '已通过', type: 'success' },
  REJECTED: { label: '已驳回', type: 'danger' },
  CANCELLED: { label: '已取消', type: 'info' },
  TODO: { label: '待处理', type: 'warning' },
  DRAFT: { label: '草稿', type: 'info' },
  PUBLISHED: { label: '已发布', type: 'success' },
  QUEUED: { label: '已排队', type: 'primary' },
  SENT: { label: '已发送', type: 'success' },
  DELIVERED: { label: '已送达', type: 'success' },
  READ: { label: '已读', type: 'success' },
  UNREAD: { label: '未读', type: 'warning' },
  PAID: { label: '已结清', type: 'success' },
  PARTIAL_PAID: { label: '部分已缴', type: 'warning' },
  OVERDUE: { label: '已逾期', type: 'danger' },
  PENDING: { label: '待缴费', type: 'info' },
  WARNING: { label: '待跟进', type: 'warning' },
  DANGER: { label: '高风险', type: 'danger' },
  INFO: { label: '提醒', type: 'info' },
  NORMAL: { label: '正常', type: 'success' },
  LATE: { label: '迟到', type: 'warning' },
}
